### ISSUE TITLE
Placing Liquid DNA from Forestry/Binnies Mod in Barrel

### ISSUE THREAD

**Issue by DoughnutDev** [shadowfacts/YeOldeTanks#2] opened 2015-10-13 21:01 UTC
I am using the latest of Ye Olde Tanks, Forestry and Binnies Mod and when I place the liquid DNA in a barrel it crashes. Here is the crash report. http://pastebin.com/xZFuzkAD

**Comment by shadowfacts** [comment] 2015-10-13 22:38
Duplicate of #1. Update is coming shortly.

**Closed as completed** 2015-10-13 22:40 UTC
Labels: duplicate

**Comment by shadowfacts** [comment] 2015-10-14 00:18
[1.0.2](http://minecraft.curseforge.com/projects/ye-olde-tanks/files/22623010) has been uploaded to CF.
